language: python
python: 3.6
install:
  - pip install pytest-cov
  - pip install requests
script:
  - pytest --cov=./ --cov-report=xml
  - bash <(curl https://codecov.io/bash)
  - cd src
  - python request.py
